# Generated by Django 6.0.2 on 2026-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida'), ('AJU', 'Ajuste')], max_length=3)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='nota')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='referencia')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('unidad', models.CharField(choices=[('UN', 'Unidad'), ('MI', 'Millar'), ('PA', 'Estiba'), ('M2', 'Metro cuadrado')], default='UN', max_length=2, verbose_name='unidad de venta')),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='precio unitario (COP)')),
                ('stock', models.IntegerField(default=0, verbose_name='stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
