# Generated by Django 6.1 on 2026-09-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'permissions': [('gestionar_inventario', 'Puede gestionar el inventario')]},
        ),
    ]
