# Generated by Django 6.0.2 on 2026-08-13 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre o razón social')),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT / cédula')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('ciudad', models.CharField(blank=True, max_length=60, verbose_name='ciudad')),
                ('direccion', models.CharField(blank=True, max_length=160, verbose_name='dirección')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=12, unique=True, verbose_name='número')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Confirmado'), ('DES', 'Despachado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('direccion_entrega', models.CharField(blank=True, max_length=160, verbose_name='dirección de entrega')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='precio unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'ítem',
                'verbose_name_plural': 'ítems',
            },
        ),
    ]
