# Generated by Django 6.1 on 2026-09-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado'], 'permissions': [('gestionar_pedidos', 'Puede gestionar clientes y pedidos')]},
        ),
    ]
